### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by ThomasMlh**

### CODE REVIEW

**Review by Sarahshr — DISMISSED** [review]
good

**Comment by Fx-Colliot** [comment]
ok very good

**Review by Fx-Colliot — DISMISSED** [review]
ok very good

**Review by Sarahshr — DISMISSED** [review]
ok

**Review by Fx-Colliot — DISMISSED** [review]
ok

**Review by Sarahshr — APPROVED** [review]
c'est ok

**Review by Fx-Colliot — APPROVED** [review]
c'est bon

**Review by LoicBrassart — APPROVED** [review]
Saw No Evil

**Pull request merged**
