### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by ThomasMlh**

### CODE REVIEW

**Review by Sarahshr — DISMISSED** [review]
it's ok for me

**Review by Fx-Colliot — DISMISSED** [review]
good

**Review by Sarahshr — DISMISSED** [review]
good

**Review by Fx-Colliot — DISMISSED** [review]
ok

**Review by LoicBrassart — CHANGES_REQUESTED** [review]
I may be wrong, but you don't use `cgu.pdf`, do you ? If you don't, please remove it

**Comment by LoicBrassart** [comment]
No no no, you re-need a group member validation :p 
(Leave my :sunglasses: emoji alone !)

**Review by Fx-Colliot — APPROVED** [review]
ok

**Review by LoicBrassart — APPROVED** [review]
No More Evil ! \o/

**Review by Sarahshr — APPROVED** [review]
good

**Pull request merged**
