### PR TITLE
 added SoulMusics and component

### PR DESCRIPTION
**Pull request by Fx-Colliot**

### CODE REVIEW

**Review by ThomasMlh — DISMISSED** [review]
It's ok for me ! Nice 👍

**Review by LoicBrassart — DISMISSED** [review]
Saw no Evil
On the other hand, you could have created only one component with a "needle" (for example) prop, taking the kind of music to search, it'd have been a lot more maintainable

**Review by ThomasMlh — APPROVED** [review]
It's ok 👍

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
