### PR TITLE
Newplayer

### PR DESCRIPTION
**Pull request by Fx-Colliot**
new player style

### CODE REVIEW

**Review by Sarahshr — DISMISSED** [review]
it's ok for me

**Comment by LoicBrassart** [comment]
I'm not assigned but I suppose I must review it? I'm on it!

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by Sarahshr — APPROVED** [review]
it's good

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
