### PR TITLE
Hotfix nav for google chrome

### PR DESCRIPTION
**Pull request by ThomasMlh**
The Input wasn't displayed correctly on Google Chrome.
I corrected it.

### CODE REVIEW

**Review by Sarahshr — DISMISSED** [review]
it's good for me

**Review by LoicBrassart — DISMISSED** [review]
Saw no Evil !

**Review by Sarahshr — APPROVED** [review]
good !

**Review by LoicBrassart — APPROVED** [review]
Still no Evil !

**Pull request merged**
