### PR TITLE
 added SweetMusics.jsx in homepage and component in Home.jsx

### PR DESCRIPTION
**Pull request by Fx-Colliot**

### CODE REVIEW

**Review by ThomasMlh — DISMISSED** [review]
It's ok for me ! Nice 👍

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by ThomasMlh — DISMISSED** [review]
It's ok 👍

**Review by ThomasMlh — APPROVED** [review]
It's ok ! 👍

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
